CMake: Set OpenGL_GL_PREFERENCE to LEGACY
The recommended value to be future-proof is GLVND, but we're not ready for it
just yet:
```
/usr/bin/ld: CMakeFiles/lugaru.dir/Source/Graphic/Stereo.cpp.o: undefined reference to symbol 'glStencilOp'
/usr/bin/ld: /usr/lib64/libGL.so.1: error adding symbols: DSO missing from command line
```

Fixes #108.