ImageIO: fix invalid conversion
Fixes:
Source/Utils/ImageIO.cpp:125:27: error: invalid conversion from 'int' to 'boolean' [-fpermissive]
     cinfo.quantize_colors = 0;
                           ^

quantize_colors type is bool, so it must be initialized to TRUE or FALSE.

Signed-off-by: Romain Naour <romain.naour@gmail.com>

(cherry picked from commit bb543993bb6f1eb76519a395d9a0a10ee777d160)