Rename DATADIR to DATA_DIR to avoid conflict
On MinGW it would error out with:

Source/Utils/Folders.cpp:33:45: error: expected primary-expression before ';' token
 const std::string Folders::dataDir = DATADIR;
                                             ^

The issue seems to be that MinGW (and likely MSVC) is case insensitive
and would see DATADIR as conflicting with dataDir.